### ISSUE TITLE
Copyright status of diminish.el and GNU ELPA

### ISSUE THREAD

**Issue by skangas** [myrjola/diminish.el#15]
Hi!

Looking closer at the copyright status of this package, I noticed that the copyright header says ";; Copyright (C) 1998 Free Software Foundation, Inc.".  Do you know if that means that Will Mengarini has assigned copyright to the FSF?

If that is true, and he is the sole author of this code before it entered git, we only have two significant contributors. This would mean that we could add it to GNU ELPA, if you agreed to also assign copyright to the FSF (if you haven't already).

If that is not true, we could still add it to GNU ELPA, but we would need copyright assignments from both of you.

Adding it to GNU ELPA would be useful, as it opens the possibility for shipping diminish.el with Emacs itself in the future.

What do you think?

**Comment by myrjola** [comment]
I would be happy to assign copyright, but I’m unsure about Will’s situation. How can we verify if he has filed the paper work?

Here’s an excerpt from email correspondence between me and Will in 2015. It seems the package has been part of Emacs at some point. I’m unaware of why it has been removed.

> I implemented diminish.el more than 16 years ago for a version of Emacs
(19, which is 6 major versions ago) that didn't have lighters.  That
version of diminish.el, which is the version on my web page, includes a
very short story -- sort of a moody philosophical reflection -- which
is woven into the code in a way that links it to the code's functions.
>
> When I sent diminish.el to Richard Stallman, he incorporated
it into official Emacs, but also ripped out the short story,
because it would have interfered with maintenance programming.
He was right about that, of course, but I've left the /original/
diminish.el on my web page just because I liked the story.
>
> My version has /never/ been maintained; as soon as diminish.el
was incorporated into Emacs, the official Emacs version
became the maintained version.  So that's the version you'll
need to find and to which you'll need to submit a patch.

**Comment by skangas** [comment]
> I would be happy to assign copyright, but I’m unsure about Will’s situation. How can we verify if he has filed the paper work?

First of all, excellent. Thank you for agreeing to do that.

I will see what I can find out regarding Will's papers. If we can't find his papers on file, I could email him and ask him if he would be willing to sign them too.

> Here’s an excerpt from email correspondence between me and Will in 2015. It seems the package has been part of Emacs at some point. I’m unaware of why it has been removed.
> 
> > I implemented diminish.el more than 16 years ago for a version of Emacs
> > (19, which is 6 major versions ago) that didn't have lighters.  That
> > version of diminish.el, which is the version on my web page, includes a
> > very short story -- sort of a moody philosophical reflection -- which
> > is woven into the code in a way that links it to the code's functions.
> > When I sent diminish.el to Richard Stallman, he incorporated
> > it into official Emacs, but also ripped out the short story,
> > because it would have interfered with maintenance programming.
> > He was right about that, of course, but I've left the /original/
> > diminish.el on my web page just because I liked the story.
> > My version has /never/ been maintained; as soon as diminish.el
> > was incorporated into Emacs, the official Emacs version
> > became the maintained version.  So that's the version you'll
> > need to find and to which you'll need to submit a patch.

Interesting. Though I can find no such file in emacs.git: `git log --all --full-history -- "**/diminish.el"` yields no matches. I have no idea what happened there; Emacs 19 was half a lifetime ago. Maybe further archeology is needed.

**Comment by myrjola** [comment]
I started looking into signing the papers. I need to ask my employer if I need their permission to assign copyright.

> I will see what I can find out regarding Will's papers. If we can't find his papers on file, I could email him and ask him if he would be willing to sign them too.

Thanks for looking into this!

**Comment by skangas** [comment]
I thought I posted here yesterday, but it turns out that we do have Will's papers on file, so it's only yours that we are missing now. As you probably saw I emailed you about the copyright assignment already.

Let me know if you need anything else!

**Comment by myrjola** [comment]
Thank you for finding the best possible place for the diminish package! Today, I got green light from my employer. I sent the form you provided to assign@gnu.org.

What happens after I have filled in the form GNU responds with? Since I'm terribly busy at this time, could you Stefan merge diminish into ELPA?

**Comment by skangas** [comment]
That's excellent news, indeed.

Yes, I will be happy to take charge of getting this into GNU ELPA. Please just confirm here or via e-mail when you have the confirmation that your copyright assignment has been approved, and I'll take care of the rest.

**Comment by myrjola** [comment]
After assigning copyright, Diminish is now released to https://elpa.gnu.org/packages/diminish.html.
