### ISSUE TITLE
Do I need to put diminish in with-eval-after-load?

### ISSUE THREAD

**Issue by yuzumx** [myrjola/diminish.el#6]
Hello

I will use some lazy loading:
```
(add-hook 'after-init-hook 'which-key-mode)
```

In this case do I need to put diminish in with-eval-after-load?
e.g.:
```
(with-eval-after-load 'which-key
  (diminish 'which-key-mode))
```

Thank you.

**Comment by myrjola** [comment]
You can diminish a mode at any time. Calling `diminish` modifies the `minor-mode-alist` variable which is used for rendering the modeline.

**Comment by trev-dev** [comment]
For anyone else searching:

I have a bunch of lazy-loaded modes that diminish seems to be missing. This is probably because this `minor-mode-alist` is being updated after the initial call for `diminish`

```elisp
(defun td/diminish-modes ()
  (dolist (mode '((company-mode)
                  (eldoc-mode)
                  (hs-minor-mode)
                  (org-indent-mode)
                  (tree-sitter-mode . "TS")
                  (undo-tree-mode)
                  (visual-line-mode)
                  (which-key-mode)
                  (whitespace-mode)
                  (yas-minor-mode)))
    (diminish (car mode) (cdr mode))))

(td/add-setup 'diminish
  (add-hook 'after-init-hook #'td/diminish-modes))
```

I will have to re-think how to implement diminish. I suppose this is why packages like `use-package` have their own implementation :)
